### ISSUE TITLE
Allow nullable values for Create PSBT requests

### ISSUE THREAD

**Issue by NicolasDorier** [junderw/NBXplorer.NodeJS#11]
Changes in last version treat optional parameters such as `rbf`, `discourageFeeSniping`, `version`, `lockTime` as randomized to protect privacy of the creator of the PSBT.

**Comment by junderw** [comment]
So is this how it changed?

If specified: follow the specified value.
If not specified: set a default value (like rbf: true)
If specified as null: randomized for privacy

**Comment by junderw** [comment]
So I am wondering what the difference of

- `{ rbf: true ... }`
- `{ ... } // no rbf anywhere in the JSON string sent in POST request`
- `{ rbf: null ... }`

**Comment by NicolasDorier** [comment]
null or not specified are the same.

The idea is: If the user has a preference, use it. Else (null or undefined), just take a good random.

**Comment by junderw** [comment]
In that case no change is necessary.

currently all those parameters are `?` which means "or undefined".

I can document the fact of randomization when adding the disableFingerprint thing in #12
