### ISSUE TITLE
Breaking change in NBXplorer

### ISSUE THREAD

**Issue by NicolasDorier** [junderw/NBXplorer.NodeJS#9]
I rarely do breaking change, this might be the first but:

```
export interface RebaseKeyPath {
  masterFingerprint: string;
  accountKey: string;
  accountKeyPath: string;
}
```

Should now be 

```
export interface RebaseKeyPath {
  accountKey: string;
  accountKeyPath: string;
}
```

Where `accountKeyPath` does not represent a keypath anymore but a rootedkeypath (eg. `ab5ed9ab/49'/0'/0'`).

Treating the masterFingerprint aside of the keypath is just confusing.

**Comment by junderw** [comment]
Fixed in v2.0.0

I'm going to add a list of all the version combinations I've manually tested in the README lol.
